### ISSUE TITLE
Small icons in terminal

### ISSUE THREAD

**Issue by Nequo** [Iosevka-Mayukai/Iosevka-Mayukai#2]
Hey, thanks for putting this font together, it looks great!

I am having 2 issues that I think are related.

1. In Kitty terminal, Nerd font icons are very small when using the font
2. In Gnome Terminal, the nerd-patched font doesn't appear. The regular font does and has icons (uninstalled the nerd font and did a refresh of the fc-cache) but they are also small.

I installed the font as per the readme, copying it into `~/.local/share/fonts` then running `sudo fc-cache -fv`. It appears when I do an `fc-list`.

No worries if the repo does not intend on maintaining a variant that is compatible with terminal emulators, just thought I would ask :) Happy to help with testing and submit any necessary info/screenshots.

**Comment by fbernier** [comment]
I, too, am experiencing tiny icons in [waybar[(https://github.com/Alexays/Waybar). I am not 100% certain but I believe it only started with 5.0+.

Here's an example: 
![image](https://user-images.githubusercontent.com/147585/123575638-2aef5800-d7a0-11eb-9b33-b20f69fba400.png)

Thanks for this font btw!

**Comment by GulajavaMinistudio** [comment]
I'm sorry about the bugs. I'm using [Nerd Font Patcher](https://github.com/ryanoasis/nerd-fonts) here, and dont know it cause some problem for latest Iosevka upstream version. Iosevka Mayukai 5.x is based from Iosevka 7.x . Maybe you can try build it yourself, with our provided build plans here [Iosevka Mayukai Build Plans](https://github.com/Iosevka-Mayukai/HowToBuild) and check the iosevka-v7 folder .

Here my screenshot for Iosevka Mayukai with glyph icon. Maybe you can try resize the font terminal settings to 11 or 12 ? 
![Screenshot_2021-07-06_10-50-59](https://user-images.githubusercontent.com/11639412/124539650-15d19380-de48-11eb-8eb5-d989424f9bc6.png)

**Comment by GulajavaMinistudio** [comment]
I'm sorry for problem caused on Zsh theme with Powerlevel10K. I think you should try this tips from Powerlevel10K page ? Hope it can be fixed.
[https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols](https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols)

> I, too, am experiencing tiny icons in [waybar[(https://github.com/Alexays/Waybar). I am not 100% certain but I believe it only started with 5.0+.
> 
> Here's an example:
> ![image](https://user-images.githubusercontent.com/147585/123575638-2aef5800-d7a0-11eb-9b33-b20f69fba400.png)
> 
> Thanks for this font btw!

**Comment by GulajavaMinistudio** [comment]
Closed because no further response from reporter.
