### ISSUE TITLE
[Breaking] Iosevka 11.x version break ligature support in Nerd Font Patcher

### ISSUE THREAD

**Issue by GulajavaMinistudio** [Iosevka-Mayukai/Iosevka-Mayukai#5]
There is compatibility issue in Nerd Font Patcher for Iosevka 11 or up version. Font that have been patched with Nerd Font Patcher, cannot show ligature if use it inside text editor. So for now, if you want use Iosevka Mayukai font for text editor, just install or copy font file inside "ttf" folder. And don't install "nerd-patched-ttf" because it will remove ligature support in your text editor.

If you want to use Iosevka Mayukai for Terminal or Shell Prompt, you can install font inside "nerd-patched-ttf" and "ttf" folders. And then set this font in your Terminal Settings or Shell prompt in your operating system.

**Comment by UnderCooled** [comment]
I've updated to Mayukai to v5.7.2, in nvy (a neovim Windows GUI frontend) ligature still working.
![image](https://user-images.githubusercontent.com/161503/147624064-80dc3135-5ff2-41e8-96a0-37043af2c103.png)

**Comment by GulajavaMinistudio** [comment]
Recently there are some report that latest update Iosevka font, version 11.x and newer, break compatibility with font patcher from adding some glyph and keeping ligature. If you are install from "ttf" and "nerd-patched-ttf" folder, ligature dont work in VS Code editor in Linux and other os.

And there are some Issue in Nerd Font repository too. Where font patcher break some ligature and built in glyph.
[https://github.com/ryanoasis/nerd-fonts/issues/694](https://github.com/ryanoasis/nerd-fonts/issues/694)

**Comment by GulajavaMinistudio** [comment]
Update new release and make note about work around for this bug in changelog.
[Iosevka Mayukai v5.7.3](https://github.com/Iosevka-Mayukai/Iosevka-Mayukai/releases/tag/v5.7.3)

**Comment by GulajavaMinistudio** [comment]
Fix with new release and patched with with Font Patcher 2.2.0 RC , and separate build for Code Editor and Terminal usage.
[Iosevka Mayukai v5.8.0](https://github.com/Iosevka-Mayukai/Iosevka-Mayukai/releases/tag/v5.8.0)
