### ISSUE TITLE
Using nerd font patched v5.7.2 in Windows 10, powerline symbols are too wide in some terminal/editor.

### ISSUE THREAD

**Issue by UnderCooled** [Iosevka-Mayukai/Iosevka-Mayukai#6]
![image](https://user-images.githubusercontent.com/161503/147624300-d1d28ee6-8097-4945-bd8e-dfb91dc9fe4d.png)

Only in Wezterm, those symbols are correct, and the font name is "Iosevka Mayukai Codepro" in most Windows programs, this is system Notepad font setting screenshot:

![image](https://user-images.githubusercontent.com/161503/147624909-f368ba7f-4606-4df6-8b8c-8e1458792c48.png)

You can see that I only have nerd font patched version installed in my system:

![image](https://user-images.githubusercontent.com/161503/147624634-7a581e24-8944-4d21-93e3-8386cef9496f.png)

Only in ConEmu the font name is "Iosevka Nerd Font":

![image](https://user-images.githubusercontent.com/161503/147624705-e5ca1a67-341e-4417-b737-d4a20239b266.png)

But powerline symbols are also too wide:

![image](https://user-images.githubusercontent.com/161503/147624941-79d8096d-9c42-4043-bfe1-9bf06310efdf.png)

In previous version (before "Slimming down Nerd patched files"), I was using the "Mono Windows Compatible", in that case, powerline symbols are correct, but the rest of nerd font "icons" is too small:

![image](https://user-images.githubusercontent.com/161503/147625218-ad6deec8-3ff3-492a-ae75-db03258029de.png)

**Comment by GulajavaMinistudio** [comment]
Maybe I should repatching this font again with adding some Monospace variant, so there's no double width size for glyph inside Terminal.

**Comment by UnderCooled** [comment]
> Maybe I should repatching this font again with adding some Monospace variant, so there's no double width size for glyph inside Terminal.

Is it possible to keep nerd font icons bigger like in v5.7.2, but powerline symbols in monospaced width?

**Comment by GulajavaMinistudio** [comment]
> Is it possible to keep nerd font icons bigger like in v5.7.2, but powerline symbols in monospaced width?

I have uploaded new build and repatching this new build. And also make Mono variant available in Nerd Font too. Hope it can fix the problem. 

[Iosevka Mayukai Release 5.7.3](https://github.com/Iosevka-Mayukai/Iosevka-Mayukai/releases/tag/v5.7.3)

I have try different config to patching it, but the result is different and make some confusion, because latest bugs in font patcher that remove default ligature. I have make some note in Readme and changelog as well for work around to resolve this.

**Comment by UnderCooled** [comment]
I'm using v5.7.3 mono variant now, powerline symbols are fine, but other icons become smaller.
I found out [Sarasa Mono SC Nerd](https://github.com/laishulu/Sarasa-Mono-SC-Nerd) (a CJK programming font based on **Iosevka** and Source Han Sans) solved this issue:

![image](https://user-images.githubusercontent.com/161503/147716305-b528ab2d-11ac-4874-b562-3ce1d195be66.png)
*Mayukai Codepro Mono v5.7.3*

![image](https://user-images.githubusercontent.com/161503/147716321-a7072cae-136e-4116-a3cc-9875c0d5e3ea.png)
*Sarasa Mono SC Nerd*

Their powerline symbols are correct, and icons are bigger, because it's a CJK font, it misses some icons.

And there's another difference in this two patched font if we zoom in:

![image](https://user-images.githubusercontent.com/161503/147716610-7f5f4499-3f1c-4300-83e8-4661f41fc632.png)
*Mayukai at top, screenshot in nvy code editor, that thin cyan line could be nvy's font anti-alias issue*

![image](https://user-images.githubusercontent.com/161503/147716933-53e767ef-41f3-4167-8b5e-fd6ce2cb4b3c.png)
*Mayukai at top, screenshot in Windows Terminal*

The powerline symbols in Mayukai Mono seems not tall enough.

Here's Sarasa Mono SC Nerd patch [source](https://github.com/laishulu/Sarasa-Mono-SC-Nerd/blob/master/scripts/font-patcher.patch) for the reference.

**Comment by GulajavaMinistudio** [comment]
Thank you for reference for Sarasa font patcher. I will check it out.

I tried Mono variant on mayukai codepro, and  this glyph icon look smaller if i use Mono variant. But if i use non mono variant , icon look bigger and correct. 

Hope nerd font patcher can resolve this issue, and i have add issue in their repo too.

**Comment by GulajavaMinistudio** [comment]
Recently i discovered that this bugs only happen in Iosevka version 11. Older version like Iosevka 10 and 9 , nerd font patcher behave normally and not causing bugs.

**Comment by GulajavaMinistudio** [comment]
Fix with new release and patched with with Font Patcher 2.2.0 RC , and separate build for Code Editor and Terminal usage.
[Iosevka Mayukai v5.8.0](https://github.com/Iosevka-Mayukai/Iosevka-Mayukai/releases/tag/v5.8.0)
